Algoritmo "lista05_C"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/11/2019
Var

vet30: vetor [0..29] de real
i: inteiro

Inicio

para i de 0 ate 29 faca
  vet30[i]<- i^2
fimpara

para i de 0 ate 29 faca
  escreva(vet30[i])
fimpara

Fimalgoritmo